services:
  misp-flare:
    build: .
    container_name: misp_flare
    image: misp_flare:latest
    environment:
      - AIS_KEY_PATH=${AIS_KEY_PATH:-/opt/mtc/config/client.key}
      - AIS_CERT_PATH=${AIS_CERT_PATH:-/opt/mtc/config/client.crt}
      - MISP_KEY=${MISP_KEY:-MISP_API_KEY}
      - COLLECTION=${COLLECTION:-AIS}
    entrypoint: "/run.sh"
