services:
  misp-flare:
    build: .
    container_name: misp_flare
    image: misp_flare:latest
    environment:
      - AIS_KEY_PATH=${AIS_KEY_PATH:-/opt/mtc/config/client.key}
      - AIS_CERT_PATH=${AIS_CERT_PATH:-/opt/mtc/config/client.crt}
      - AIS_P12_PATH=${AIS_P12_PATH:-/opt/mtc/config/client.p12}
      - AIS_P12_PASS=${AIS_P12_PASS:-p12_password}
      - AIS_P12_ALIAS=${AIS_P12_ALIAS:-1}
      - USE_CLIENT_KEY=${USE_CLIENT_KEY:-true}
      - MISP_SERVER=${MISP_SERVER:-localhost}
      - MISP_KEY=${MISP_KEY:-MISP_API_KEY}
      - COLLECTION=${COLLECTION:-AIS}
      - FREQUENCY=${FREQUENCY:-240}
      - READ_TIMEOUT=${READ_TIMEOUT:-0}
      - TIMEZONE=${TIMEZONE:-UTC}
      - JAVA_HEAP_SIZE=${JAVA_HEAP_SIZE:-6G}
    entrypoint: "/run.sh"
